const rectangle = {x1: Math.random() * (200), y1: Math.random() * (200), x2: 400, y2: 300};
const topPoint = {};
const leftPoint = {};
const rightPoint = {};
const center = {};

topPoint.x = (rectangle.x2 - rectangle.x1) / 2 + rectangle.x1;
topPoint.y = rectangle.y1;
leftPoint.x = rectangle.x1;
leftPoint.y = rectangle.y2;
rightPoint.x = rectangle.x2;
rightPoint.y = rectangle.y2;
const h = rectangle.y2 - rectangle.y1;
const a = rightPoint.x -  leftPoint.x;
const b = Math.sqrt (Math.pow(a / 2, 2) + Math.pow(h, 2));
const r = (a * h) / (a + 2 * b);
center.x = topPoint.x;
center.y = rightPoint.y - r;
console.log(`Right point coordinate ${rightPoint.x};  ${rightPoint.y}`);
console.log(`Left point coordinate ${leftPoint.x};  ${leftPoint.y}`);
console.log(`Top point coordinate ${topPoint.x};  ${topPoint.y}`);
console.log(`Circle center coordinate ${center.x};  ${center.y}`);

let canvas = document.getElementById("canvas");
let ctx = canvas.getContext("2d");
ctx.strokeStyle = "green";
ctx.strokeRect(rectangle.x1, rectangle.y1, rectangle.x2 - rectangle.x1, rectangle.y2 - rectangle.y1);
ctx.strokeStyle = "red";
ctx.moveTo(leftPoint.x, leftPoint.y);
ctx.lineTo(topPoint.x, topPoint.y);
ctx.lineTo(rightPoint.x, rightPoint.y);
ctx.lineTo(leftPoint.x, leftPoint.y);
ctx.stroke();
ctx.beginPath();
ctx.arc(center.x, center.y, r, 0, 2 * Math.PI, false);
ctx.lineWidth = 1;
ctx.strokeStyle = 'blue';
ctx.stroke();
ctx.fillStyle = 'lightblue';
ctx.fill();
ctx.save();
